#https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-net
name: dotnet package
on:
  - push
jobs:
  display-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version:
          - "8.x"
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Display dotnet version
        run: dotnet --version

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version:
          - "8.x"
        tfm:
          - net8.0
          - netstandard2.0
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: dotnet restore
        run: dotnet restore
      - name: dotnet build ./src/PSSharp.WindowsUpdate.Commands
        run: dotnet build --configuration Release --framework ${{ matrix.tfm }}
      - name: dotnet test
        run: dotnet test --no-restore --verbosity normal --framework ${{ matrix.tfm }}
      - name: dotnet publish
        run: dotnet publish ./src/PSSharp.WindowsUpdate.Commands --configuration Release --output ./publish --framework ${{ matrix.tfm }}
